### ISSUE TITLE
Issue with nxos_portchannel on Nexus 3K, ref issue #5

### ISSUE THREAD

**Issue by RNanney** [jedelman8/nxos-ansible#18]
Hello,

I'm getting the following stack trace when trying to configure a port channel.

http://pastebin.com/86gaXTYF

I understand that the issues stems from the Nexus 3K not returning structured data, but it looks like you added code to account for that. However, the device.show() function is detecting the clierror and raising the exception before it gets back to feature_enabled function.

I was able to play around with this and get a work around by adding the following code.

```
    facts = get_facts(device)
    platform = facts['platform']
    n3k = platform[6] == '3'
    if n3k:
        data = device.show(command, text=True)
        data_dict = xmltodict.parse(data[1])
        table = data_dict['ins_api']['outputs']['output']
        manual_list = table['body'].split('\n')
```

I think this is an ineffieient way of doing this because in my situation I will be sequencing through multiple interfaces which means facts will be gathered everytime.

I wanted to get your thoughts on adding get_features_list() function to get_facts() and then modifying the nxos_portchannel module to accept a facts=true parameter to allow it to bypass the feature look up.  Then within the play I could do something like, "when: lacp" which would pull the value from the facts.

The main goal is to avoid doing this lookup everytime.

Please let me know your thoughts.

Kind regards,
Robert

**Comment by jedelman8** [comment]
Thanks for opening this issue up.  Traveling this week, but will get to it ASAP.

**Comment by RNanney** [comment]
Thanks!
I have been adding some work arounds and just wanted to share those with you so you can see what I'm doing before I submit a PR.

https://github.com/RNanney/nxos-ansible/tree/nxos_vpc_int

https://github.com/RNanney/pycsco/tree/facts_and_features

Please let me know if you have any feedback on what I have done so far.

-Robert

**Comment by mzbenami** [comment]
Hey Robert,

I'm working with @jedelman8 on this repo. Would you mind opening a PR for both the pycsco and nxos-ansible changes? It will be easier to see the aggregation of all changes in one place and comment on specific sections of code. You can still make additional changes based on our comments if necessary before we merge it.

Thanks!
Michael

**Comment by jedelman8** [comment]
Rob, would you mind re-posting the stack trace if you still have it too?

**Comment by jedelman8** [comment]
BTW, is your goal to not check to see if a feature is enabled and "trust" the user knows it is, to eliminate that API request?

**Comment by RNanney** [comment]
I don't have a stack trace, I'll see if I can re-create it.  The main goal is to get the facts as a pre-task, register those, then reference those when you need to do something that requires a feature.

**Comment by EvgeniyV** [comment]
Hi!
I'm working with: Cisco Nexus5548 Chassis,System version: 7.2(1)N1(1), BIOS: version 3.6.0
I am trying to create portchannel and VPC

```
      - name: Ensure port-channel is created, add two members, and set to mode on
        nxos_portchannel: host={{ inventory_hostname }} 
                          group={{ portchannel.group }}
                          members=['Eth1/26','Eth1/27']
                          mode={{ portchannel.mode }}
                          state=present
```

but get exception on checking feature `lacp` is on:

```
Traceback (most recent call last):
  File "/home/varfolomeiev/.ansible/tmp/ansible-tmp-1451391448.41-55211464101838/nxos_portchannel", line 1855, in <module>
    main()
  File "/home/varfolomeiev/.ansible/tmp/ansible-tmp-1451391448.41-55211464101838/nxos_portchannel", line 171, in main
    if not nxapi_lib.feature_enabled(device, 'lacp'):
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/utils/nxapi_lib.py", line 1951, in feature_enabled
    data = device.show(command)
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/device.py", line 108, in show
    raise clierror
pycsco.nxos.error.CLIError: NX-OS CLI Configuration Error
Feature Name          Instance  State   
--------------------  --------  --------
Flexlink              1         disabled
amt                   1         disabled
bfd                   1         disabled
bfd_app               1         disabled
bgp                   1         disabled
...
lacp                  1         enabled 
...
vtp                   1         enabled 
wccp                  1         disabled. Structured output unsupported


FATAL: all hosts have already failed -- aborting
```

in Sandbox i see this:

```
<?xml version="1.0"?>
<ins_api>
  <type>cli_show</type>
  <version>1.2</version>
  <sid>eoc</sid>
  <outputs>
    <output>
      <clierror>Feature Name          Instance  State   
--------------------  --------  --------
Flexlink              1         disabled
amt                   1         disabled
bfd                   1         disabled
...
lacp                  1         enabled 
...
</clierror>
      <input>show feature</input>
      <msg>Structured output unsupported</msg>
      <code>501</code>
    </output>
  </outputs>
</ins_api>
```

This is a fragment code in nx_api.py lines 1950 -1976:

```
  try:
        data = device.show(command)
        data_dict = xmltodict.parse(data[1])
        table = data_dict['ins_api']['outputs']['output']
        error = table.get('clierror', None)
        ...
    except (KeyError, AttributeError):
        return check
```

Nexus version 7.2(1)N1(1)

So  on the line 1951 calling `data = device.show(command)` raise an exception `clierror` - 
 which isnt catching at all

also the same thing happened for nxos_vpc configuration

```
 - name: config portchannel10 to be the peerlink
        nxos_vpc_interface: host={{ inventory_hostname }} 
                          portchannel=30 peer_link=true
```

Exception:

```
Traceback (most recent call last):
  File "/home/varfolomeiev/.ansible/tmp/ansible-tmp-1451900723.81-137141663504457/nxos_vpc", line 1901, in <module>
    main()
  File "/home/varfolomeiev/.ansible/tmp/ansible-tmp-1451900723.81-137141663504457/nxos_vpc", line 237, in main
    if not nxapi_lib.feature_enabled(device, 'vpc'):
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/utils/nxapi_lib.py", line 1951, in feature_enabled
    data = device.show(command)
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/device.py", line 108, in show
    raise clierror
pycsco.nxos.error.CLIError: NX-OS CLI Configuration Error
Feature Name          Instance  State   
--------------------  --------  --------
Flexlink              1         disabled
amt                   1         disabled
...
vpc                   1         enabled 
vrrp                  1         disabled
vtp                   1         enabled 
wccp                  1         disabled. Structured output unsupported
```

**Comment by heathdbrown** [comment]
This should be fixed in @RNanney  https://github.com/jedelman8/nxos-ansible/pull/22 and the corresponding pycsco pull request.

The issue here is that the module is verifying lacp everytime you try to do a port-channel or vpc. instead of trusting the user to perform the check off of a gathered fact.

The gathering of facts is broken at least on 3ks in version 6.0.2.U5.2 as it can only return ASCII not JSON like on a Nexus 9k.

To get around this @RNanney made modifications to use the facts to bypass the per interface checks.

https://github.com/jedelman8/pycsco/pull/10 --> Looks like there are some merge conflicts now.
