### ISSUE TITLE
Any interest in publishing to Ansible Galaxy?

### ISSUE THREAD

**Issue by ecowden** [jedelman8/nxos-ansible#26]
I'm still a bit of an Ansible newbie, so feel free to correct anything I say. :grimacing: 

Would you have any interest in packaging this as a role and publishing it to [Ansible Galaxy](https://galaxy.ansible.com/)? It would make installation much easier. Rather than creating folders manually, consumers could just `ansible-galaxy install jedelman.nxos`. Furthermore, if people would like to create additional roles that use your nxos modules, the dependency can be managed more or less automagically through the [metadata file](https://galaxy.ansible.com/intro#meta).

I realize that this wouldn't really be a "Role," but would leverage Ansible's ability to [embed modules in roles](http://docs.ansible.com/ansible/playbooks_roles.html#embedding-modules-in-roles).

I think this would be fairly straightforward. We would need to:
- [x] Create a [metadata file](https://galaxy.ansible.com/intro#meta) to describe the role
- [x] Update documentation
- [ ] [Publish](https://galaxy.ansible.com/intro#role-galaxy) to Ansible Galaxy

I can almost certainly take this on, but I'd hate to do something that conflicts with your vision of this project. What do you think?

**Edit**: PR submitted.

**Comment by greenpau** [comment]
sounds like a great idea! :+1:
