### ISSUE TITLE
Running nxos_command on long running command appears to hit socket timeout

### ISSUE THREAD

**Issue by heathdbrown** [jedelman8/nxos-ansible#3]
https://gist.github.com/heathdbrown/4fb65e28c0bf58f37991

Running default interface eth1/1 - 44 on Nexus 3172 6.0.2.U4.3

nxos_command reports socket timeout

The operation is performed and is successful on both switches.

Before run

```
------------------------------------------------------------------------------------
Port          Name               Status    Vlan      Duplex  Speed   Type
------------------------------------------------------------------------------------
Eth1/1        test               inactive  105       Full    auto    100/1000/10GBas
Eth1/2        Configured by Sand inactive  105       Full    auto    100/1000/10GBas
Eth1/3        --                 inactive  105       Full    auto    100/1000/10GBas
Eth1/4        --                 inactive  105       Full    auto    100/1000/10GBas
Eth1/5        --                 notconnec 1         Full    auto    100/1000/10GBas
```

After run, after timeout

```
------------------------------------------------------------------------------------
Port          Name               Status    Vlan      Duplex  Speed   Type
------------------------------------------------------------------------------------
Eth1/1        test               notconnec 1         Full    auto    100/1000/10GBas
Eth1/2        Configured by Sand notconnec 1         Full    auto    100/1000/10GBas
Eth1/3        --                 notconnec 1         Full    auto    100/1000/10GBas
Eth1/4        --                 notconnec 1         Full    auto    100/1000/10GBas
Eth1/5        --                 notconnec 1         Full    auto    100/1000/10GBas
```

**Comment by jedelman8** [comment]
Okay, this isn't a huge surprise.  I've seen this during my testing (usually on 3Ks).  Ironicially, I had seen this using the nxos_interface module using the `ethernet` and `all` keywords like this:  

```
nxos_interface: interface=ethernet state=default host={{ inventory_hostname }}
```

I'll dig in and see if increasing the default timer within the Device module in the pycsco library helps.  If so, we may need to add a timer param in these modules to start with.

Will try and take a deeper look tomorrow night, but Monday is more realistic.  

Thanks (keep these coming!) :)

**Comment by heathdbrown** [comment]
Yeah I am testing the N3k platform against the module...I think I have another one but need to verify as its the nxos_switchport once I confirm I will open another one.

**Comment by jedelman8** [comment]
Can you actually try this with the `nxos_interface` module and set the `interface` param to be `all` or `ethernet`.  And set `state` to `default` or `absent`. I forgot that I increased the timeout if those keywords are used (from 30 sec to 120 sec).  Curious if this fixes what you are seeing.

I'm not able to reproduce on a 3064 at this time.  That said I have seen this happen when I was doing non-stop testing.  It may also be a control plane thing for the API.

Let me know how the test goes using `nxos_interface`.

**Comment by heathdbrown** [comment]
Looks like I am still getting the timeout error using the state: absent method

https://gist.github.com/heathdbrown/ee93cf2e7c08b3b2d647

It does perform the action it just times out waiting on the return.

**Comment by jedelman8** [comment]
Can you give me an idea of how much time it takes for this error to be thrown?

Side note: I will continue to look into this, but it will be hard because I cannot reproduce. That said, it may be good to see how many interfaces you can default without the error being thrown and take a number a few less than that for now and use in your playbooks.
