### ISSUE TITLE
nxos_copy socket time on large Bin files

### ISSUE THREAD

**Issue by aroramanish2009** [jedelman8/nxos-ansible#31]
Hi,
First of all, Thank you for this awesome work.

I was having socket time with copying larger nxos files for switch upgrades. I made the following change to the nxos_copy to adjust the http socket time. 

Not sure if this the most optimal way but it did work for me. ( please add to the Repo if you think it's fine)

---

nxos_copy 
- Added timeout to Device parameters to adjust for File Size
  def main():
  ## Added 
  sizetimeout=dict(type='int', required=True),
  )
## Added:

sizetimeout = module.params['sizetimeout']
## Edited:

device = Device(ip=host, username=username, password=password, protocol=protocol, timeout=sizetimeout)

---

In the playbook, I passed the sizetimeout as 300 second for my .bin file transfer. 

Thanks again
Manish

**Comment by jedelman8** [comment]
You should actually use nxos_file_copy instead.

**Comment by aroramanish2009** [comment]
Hi,
Yes, I saw that module after writing a note here. I will try to use that module and see if that I hit the Timeout issue in the playbook and also other tasks that depended on the completion of this task.  
Thanks
Manish
