### ISSUE TITLE
nxos_switchport on N3k 6.0.2.U4.3 throws 401 unauthorized

### ISSUE THREAD

**Issue by heathdbrown** [jedelman8/nxos-ansible#4]
nxos_switchport thows 401 unauthorized.

This can be on a port-channel or a normal ethernet port

https://gist.github.com/heathdbrown/eb72329411c12f3e2ad3

**Comment by jedelman8** [comment]
Oddly enough, I got an error when I tested this (now fixed), but you'll need to upgrade the `pycsco` package. `sudo pip install pycsco --upgrade` should do the trick.

The error you are seeing may be an issue with the `.netauth` file if you are using one? Are you testing on the same machine as the same user as your other playbooks?

To be safe, can you add the username and password params to your task? If you still get the error then, we'll dive into `nxos_switchport`. Thanks.

**Comment by heathdbrown** [comment]
I updated to pip list | grep pycsco
pycsco (0.1.9)

Still getting it when running the `nxos_switchport.`

Everything i am doing is from a vagrant box with the same .netauth...I am testing adding the username and testing.

**Comment by heathdbrown** [comment]
Alright added in the username and password parameter and its doing better.

```
TASK: [Configure int po 999 switchport] ***************************************
failed: [switch1] => {"failed": true}
msg: Ensure interface is configured to be a L2 port first before using this module.
failed: [switch2] => {"failed": true}
msg: Ensure interface is configured to be a L2 port first before using this module.

FATAL: all hosts have already failed -- aborting
```

**Comment by heathdbrown** [comment]
Updated with the layer2 step and now it works on 1 but fails on the other.

```
TASK: [Configure int po999 to be a layer 2 port] ******************************
changed: [switch1]
changed: [switch2]

TASK: [Configure int po 999 switchport] ***************************************
failed: [switch2] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1425345965.64-114887305222245/nxos_switchport", line 1902, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1425345965.64-114887305222245/nxos_switchport", line 196, in main
    existing = nxapi_lib.get_switchport(device, interface)
  File "/usr/local/lib/python2.7/dist-packages/pycsco/nxos/utils/nxapi_lib.py", line 771, in get_switchport
    data = device.show(command)
  File "/usr/local/lib/python2.7/dist-packages/pycsco/nxos/device.py", line 74, in show
    return self.sw1.send_req()
  File "/usr/local/lib/python2.7/dist-packages/pycsco/nxos/nxapi.py", line 279, in send_req
    return req.get_resp(self.req_to_string(), self.cookie, self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/pycsco/nxos/nxapi.py", line 134, in get_resp
    resp_str = resp.read()
  File "/usr/lib/python2.7/socket.py", line 351, in read
    data = self._sock.recv(rbufsize)
  File "/usr/lib/python2.7/httplib.py", line 543, in read
    return self._read_chunked(amt)
  File "/usr/lib/python2.7/httplib.py", line 597, in _read_chunked
    raise IncompleteRead(''.join(value))
httplib.IncompleteRead: IncompleteRead(8072 bytes read)

changed: [switch2]
```

**Comment by jedelman8** [comment]
Okay. Forgot to say I updated the module too. You'll need to pull it down from here on GH.

**Comment by jedelman8** [comment]
I need to stop responding on my phone, but one more thing. For this module (when working with portchannels), you should use the full interface name, i.e. port-channel999

There are only 2-3 mods where this matters and this is one of them, but it is still good practice to always use the full name.

**Comment by heathdbrown** [comment]
This was fixed a while back and tested with using the full name.
