### ISSUE TITLE
nexus-automation.yml fails as nexus_interface module is not found

### ISSUE THREAD

**Issue by abhinavmodi** [jedelman8/nxos-ansible#52]
On trying to run nexus_automation.yml with the latest code, I get the following error : 

abhinav@ubuntu:~/gitprojs/ansiblej/nxos-ansible$ ansible-playbook    -i hosts nexus-automation.yml 
ERROR: nxos_get_interface is not a legal parameter in an Ansible task or handler

If I bring back the file nxos_interface and hiding nxos_interface.py in the library, this starts to work. Is there an issue with nxos_interface.py ?

**Comment by jedelman8** [comment]
I definitely merged something that wasn't ready to be merged, but it shouldn't have affected this.  Please try again, but please note you are asking about nxos_interface and the error is about nxos_get_interface.  However, both should work.

Let me know, but do a git pull, and re-test.
