### ISSUE TITLE
nxos_command module does not support the usage of pipes in show commands

### ISSUE THREAD

**Issue by ghost** [jedelman8/nxos-ansible#6]
Hey Jason,

I am running into this issue while testing nxos_command module against Nexus3k.

{
  "ins_api": {
    "type": "cli_show",
    "version": "1.0",
    "sid": "eoc",
    "outputs": {
      "output": {
        "clierror": "",
        "input": "show interface ethernet1/2 | i Manual",
        "msg": "Pipe is not allowed for this message type",
        "code": "501"
      }
    }
  }

Thanks for your help and support.

Regards,
Ron

**Comment by jedelman8** [comment]
Please include the playbook when you post! :)

BUT, you will need the param text=true if you want to run this using the `nxos_command` module.  

Let me know how it goes.

**Comment by ghost** [comment]
Totally forgot about including the playbook. There you go

---
- name: Testing the usage of Register module in Ansible
  hosts: nexus3k1
  gather_facts: no
  connection: local
  
  tasks:
  - name: Using register command to capture the description output
    nxos_command: command='show interface Ethernet 1/2 | grep Manual' text=true host={{ inventory_hostname }} type=show
    register: description
    ignore_errors: yes
  - name: Enabling the interface using Ansible if manual from previous result
    when: description|success
    nxos_interface: interface=Ethernet1/2 description="Manual to Ansible" host={{ inventory_hostname }} admin_state=down

I did try using the parameter: text=true, but it didnt help.

Thanks,
Ron

**Comment by jedelman8** [comment]
Ron,

Looks like this is a limitation of the API.  You can verify stuff like this using the NX-API sandbox as well.  

Sorry dude! :)
