### ISSUE TITLE
enabling feature  does not working

### ISSUE THREAD

**Issue by Hemakuma** [jedelman8/nxos-ansible#69]
It used to work, but i upgraded my code to latest release. Now when i try to enable features using ansible i get the following errors.

fatal: [spine801]: FAILED! => {"changed": false, "failed": true, "features_currently_supported": [], "invalid_feature": "lacp", "msg": "Invalid feature name."}

**Comment by jedelman8** [comment]
What device type and software version are you running?

**Comment by Hemakuma** [comment]
It looks like there is issue with the verison of nxos module.  I had this installed this copy  while back and seems like something has changed.  today I installed a fresh copy and it works fine.  Question. how do i update my old copy so that it has the newer module.

**Comment by jedelman8** [comment]
You can pull down the updates.  `git pull origin master`.  Or you can just blow it away if you don't have local changes, and just clone it again. Make sense?
