### ISSUE TITLE
Features of two words fail in nxos_feature

### ISSUE THREAD

**Issue by rogerscuall** [jedelman8/nxos-ansible#75]
I was trying to use nxos_feature to enable "nv feature" I have quoted the feature also but I have the same error:

```
failed: [n9k1] => (item=nv overlay) => {"failed": true, "item": "nv overlay"}
msg: this module requires key=value arguments (['feature=nv', 'overlay', 'state=enabled', 'host=n9k1'])
failed: [n9k2] => (item=nv overlay) => {"failed": true, "item": "nv overlay"}
msg: this module requires key=value arguments (['feature=nv', 'overlay', 'state=enabled', 'host=n9k2'])
```

Thanks.

**Comment by jedelman8** [comment]
Can you please try "nv overlay" in quotes in the playbook such as feature="nv overlay" ?

**Comment by jedelman8** [comment]
Check the feature you want to enable...quotes work as I get this:

```
failed: [n9k1] => {"failed": true, "features_currently_supported": {"bash-shell": "enabled", "bfd": 
"disabled", "bgp": "disabled", "dhcp": "disabled", "eigrp": "disabled", "evmed": "disabled", 
"fabric_mcast": "disabled", "hmm": "disabled", "hsrp_engine": "enabled", "interface-vlan": "enabled", 
"isis": "disabled", "itd": "disabled", "lacp": "enabled", "ldap": "disabled", "ldp": "disabled", "lldp": 
"enabled", "mpls_static": "disabled", "msdp": "disabled", "nat": "disabled", "nve": "disabled", "nxapi": 
"enabled", "onep": "disabled", "ospf": "enabled", "ospfv3": "disabled", "pbr": "disabled", "pim": 
"disabled", "pim6": "disabled", "private-vlan": "disabled", "privilege": "disabled", "ptp": "disabled", "rip": 
"disabled", "scheduler": "disabled", "scpServer": "enabled", "sflow": "disabled", "sftpServer": 
"disabled", "sla_responder": "disabled", "sla_sender": "disabled", "sshServer": "enabled", "tacacs": 
"disabled", "telnetServer": "disabled", "tunnel": "disabled", "udld": "disabled", "vmtracker": "disabled", 
"vni": "disabled", "vnseg_vlan": "disabled", "vpc": "enabled", "vrrp": "disabled", "vrrpv3": "disabled", 
"vtp": "disabled"}, "invalid_feature": "nv overlay"}

```

Let me know what you see.

**Comment by rogerscuall** [comment]
I can see your previous output if do: 

```
nxos_feature: feature='nv overlay' state=enabled host={{ inventory_hostname }}
```

But if I do use with_item like this:

```
---
- name: "Enabling features"
  nxos_feature: feature={{ item }} state=enabled host={{ inventory_hostname }}
  with_items:
  - ospf
  - bgp
  - pim
  - "nv overlay"
```

I got what I have in the first comment:

```
failed: [n9k1] => (item=nv overlay) => {"failed": true, "item": "nv overlay"}
msg: this module requires key=value arguments (['feature=nv', 'overlay', 'state=enabled', 'host=n9k1'])
failed: [n9k2] => (item=nv overlay) => {"failed": true, "item": "nv overlay"}
msg: this module requires key=value arguments (['feature=nv', 'overlay', 'state=enabled', 'host=n9k2'])
```

For your previous output I think that I know what is the problem, maybe your are looking to the command **show feature**  to see the list of features, and _nv overlay_ is not in that list, but definitely is an option:
<img width="474" alt="screen shot 2016-02-02 at 4 42 37 pm" src="https://cloud.githubusercontent.com/assets/5758351/12765310/14cb6d58-c9cc-11e5-8ef4-49ce2c857d7a.png">
Thanks.

**Comment by jedelman8** [comment]
Found the issue.  The API doesn't match the command to enable the feature.

If you use the API (or sandbox) and issue the command `show feature` you see all features on the box.  One of them is called `nve`.  This is what the command `feature nv overlay` toggles.  Since we use the `show feature` command via the API, this is why "nv overlay" shows as an invalid feature.

See here from the API/sandbox- 

```
  {
                "cfcFeatureCtrlName2": "nve",
                "cfcFeatureCtrlInstanceNum2": 1,
                "cfcFeatureCtrlOpStatus2": "enabled"
              },
```

We have two options:
1. remove the safety check from the module
2. add a mapper in the module that maps "nv overlay" to "nve" (and vice versa)

Will know have to check to see if there are other features this is relevant for :/ 

Thoughts on opition 1?

**Comment by rogerscuall** [comment]
I really like the safety check implemented in point 1, and this sounds more like an inconsistency in the API or NX-OS, if  so I really like point 2.
I also did a lit bit of research I connected directly to the switch and I did **show feature | json-pretty** and I got the entire output you had in the previous message and I checked feature by feature and the only one that is not matching is the one you have listed but there is another command that from my point of view should be a feature that is pretty similar and is **nv overlay evpn**.
Hope this helps.

**Comment by jedelman8** [comment]
Thanks for the checking that.  Will add a fix for this soon.  Stay tuned.
