### ISSUE TITLE
Question about facts and features

### ISSUE THREAD

**Issue by rogerscuall** [jedelman8/nxos-ansible#77]
Is there any of the module that return the features available and enabled/disabled in the device, I was reading through the libraries and I did not find one. A playbook can be implemented to gather that information but occurred to me that maybe the module nxos_get_facts is a good place to have that, that module returns info about show version, show interfaces and other things but I think that would be a good idea to retrieve as well some info about features in the box.  I'm already working in this direction but I would like to hear from if you think is something useful.

**Comment by jedelman8** [comment]
Over time, I'd like to have more get modules and not keep putting more into facts.  We can make a nxos_get_features module.  Have any interest in writing it?  If not, we will do this in the future!

**Comment by rogerscuall** [comment]
I put together yesterday one playbook to gather features something really simple with the nxos_command module, so in some way I'm cover there. Yes, I'm interested in writing modules, I'm currently trying to write one to map VLAN to VXLAN, basically I'm using your nxos_vlan and for the most part changing the name argument for the vxlan_id, to map a vlan to vxlan you need:

```
vlan 10
 vn-segment 10010
```

 I'm struggling with the debug of the module, you have a great documentation, the code is really elegant and easy to read but if you any debug tips that can share would be great, I've a lot of switches to test with different versions so that is not a problem.

**Comment by jedelman8** [comment]
I would say use module.exit_json() as much as you can and pass variables to it wherever you want to print something for normal debugging.

For example, you have a variable called `existing` and someting isn't right, so you want to debug or print existing at a point in the module.  Just do this:

```
module.exit_json(e=existing)
```

Note: the `e` can be anything.

Two vars you want to compare, i.e. existing and propsosed.  You can do:

```
module.exit_json(e=existing, p=proposed)
```

Just make sure they are in k=v format.

Gradually move the exit down in your code as you test.
