### ISSUE TITLE
issues with lookback in readme-example1 and vlan range in readme-example2

### ISSUE THREAD

**Issue by ArthurLiu888** [jedelman8/nxos-ansible#82]
I am running nxos-ansible scripts against N9k(nxos: 7.0(3) I1(2)) and ran into the issues with the example scripts.
1. It seems lookback interface without # is not recognized with the error below.
fatal: [leaf1]: FAILED! => {"changed": false, "error": "NX-OS CLI Configuration Error\nSyntax error while parsing 'show interface loopback  | xml '\n\n\nCmd exec error.. Input CLI command error. Error Found on Command Number: 1", "failed": true, "msg": "Error sending show interface loopback"}

2 Vlan ranges doesn't work. 
  Confirmed individual vlans work fine.  

TASK [ensure VLANs 1-20 and 99 exist on all switches] **************************
fatal: [leaf1]: FAILED! => {"changed": false, "failed": true, "msg": "vlan_id must be a valid VLAN ID"}

Arthur

**Comment by jedelman8** [comment]
Arthur,
1.  Can you please show what you have in your playbook ?
2. VLAN ranges are no longer supported in the VLAN module.

**Comment by ArthurLiu888** [comment]
Jason,
Thank you for the reply.
Here is my script. Bascially I simplified it to show the issue with only loopback as interface.
It is supposed to cover all loopback interfaces on this N9k.

# examples/readme-example1.yml

---
- name: example 1 - baseline
  hosts: leaf1
  
  tasks:
  - name: ensure no logical interfaces exist on the switch
    nxos_interface: interface=loopback state=absent host={{ inventory_hostname }}
  - name: ensure all Ethernet ports are admin down
    nxos_interface: interface=Ethernet admin_state=down host={{ inventory_hostname }}

**Comment by jedelman8** [comment]
Thanks, will take a look at this soon.
