### ISSUE TITLE
Unable to create logical interface on nexus

### ISSUE THREAD

**Issue by geepees2015** [jedelman8/nxos-ansible#86]
Hi,
I am trying to create a logical interface SVI on a Nexus 9396PX and running into following error :+1: 

 ansible-playbook -i hosts test1-leaf.yml -vvv
Using /etc/ansible/ansible.cfg as config file
1 plays in test1-leaf.yml

PLAY [leaf configuration] ******************************************************

TASK [create logical vlan interfaces] ******************************************
task path: /home/gp/nxos-ansible/test1-leaf.yml:15
ESTABLISH LOCAL CONNECTION FOR USER: root
stepup.com EXEC /bin/sh -c '( umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1461817876.02-56366820469356`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1461817876.02-56366820469356`" )'
stepup.com PUT /tmp/tmpNrZG3E TO /root/.ansible/tmp/ansible-tmp-1461817876.02-56366820469356/nxos_interface
dss.tor.01.303.48.gecis.io EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/env python /root/.ansible/tmp/ansible-tmp-1461817876.02-56366820469356/nxos_interface; rm -rf "/root/.ansible/tmp/ansible-tmp-1461817876.02-56366820469356/" > /dev/null 2>&1'
fatal: [stepup.com]: FAILED! => {"changed": false, "error": "NX-OS CLI Configuration Error\nSyntax error while parsing 'show interface Vlan11  | xml '\n\n\nCmd exec error.. Input CLI command error. Error Found on Command Number: 1", "failed": true, "invocation": {"module_args": {"admin_state": "up", "description": null, "duplex": null, "host": "stepup.com", "interface": "vlan11", "mode": null, "password": "xyz", "port": null, "protocol": "http", "speed": null, "state": "present", "username": "admin"}, "module_name": "nxos_interface"}, "msg": "Error sending show interface Vlan11"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test1-leaf.retry

PLAY RECAP *********************************************************************
stepup.com : ok=0    changed=0    unreachable=0    failed=1  
# Configs
## [root@ nxos-ansible]# more test1-leaf.yml 
- name: leaf configuration
  hosts: leaf
  connection: local
  gather_facts: no
  
  tasks:
  
    #############################################################
    # Layer 3 Configuration
    #############################################################
  - name: create logical vlan interfaces
    nxos_interface: interface=vlan11 host={{ inventory_hostname }} username=admin password=xyz
  - name: assign IP addresses
    nxos_ipv4_interface: interface=vlan11 ip_addr=10.99.4.2 mask=24 host={{ inventory_hostname }} username=admin password=xyz
# Hosts file

more hosts
[all:vars]
ansible_connection = local

[leaf]
stepup.com 

Appreciate your help.

Thanks,
GP

**Comment by jedelman8** [comment]
Can you make sure the feature called interface-vlan is enabled on the switch?

Command: "feature interface-vlan"

**Comment by geepees2015** [comment]
Hi Jason,
I have interface-vlan enabled on the switch.
One thng I noticed is that , if I create 'interface vlan 11' manually on the switch, then the script runs about creating the ip address for vlan . Does the task just create the attributes under SVI or does it create the SVI as well ?

Thanks,
GP

**Comment by jedelman8** [comment]
`nxos_interface` is required to create/remove the SVI and `nxos_ipv4_interface` is used manage/add/remove the IP address.

**Comment by geepees2015** [comment]
I just tried the nxos_interface task and it keeps failing. Not sure what needs to be done next.

I was gonig through the nxos_interface.py file and it looks like you do enable 'feature-vlan' if not present.

**Comment by geepees2015** [comment]
Any reason on why the task throws error?

**Comment by jedelman8** [comment]
Can you run it in check mode + verbose to see what commands are being sent?

`ansible-playbook playbook.yml -v --check`

Can you also provide the output of `show interface Vlan11 | xml` and `show interface Vlan11 | json` ?

**Comment by geepees2015** [comment]
[root@stepup nxos-ansible]# ansible-playbook -i hosts test2-leaf.yml -v --check
Using /etc/ansible/ansible.cfg as config file

PLAY [leaf configuration] ******************************************************

TASK [create logical vlan interfaces] ******************************************
fatal: [stepup.com]: FAILED! => {"changed": false, "error": "NX-OS CLI Configuration Error\nSyntax error while parsing 'show interface Vlan11  | xml '\n\n\nCmd exec error.. Input CLI command error. Error Found on Command Number: 1", "failed": true, "msg": "Error sending show interface Vlan11"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test2-leaf.retry

PLAY RECAP *********************************************************************
stepup.com : ok=0    changed=0    unreachable=0    failed=1   

stepup.com(config)# show interface vlan 11 | json
                                                       ^
Invalid range at '^' marker.
stepup.com(config)# show interface vlan 11 | xml
                                                      ^
Invalid range at '^' marker.

Looks like nothing is getting created.

**Comment by jedelman8** [comment]
Okay, this is odd and don't know how this wasn't caught earlier, but a change in the modules seem to created this issue.  That said, we are in the process of migrating the nxos modules to Ansible core, and for all intents and purposes this repo is slowly being phased out.  

10 of the modules are already migrated and nxos_interface is one of them.

Please see here: https://github.com/ansible/ansible-modules-core/tree/devel/network/nxos

To use them, you do need to install Ansible from source and ensure you are using Ansible 2.1.  

```
$ git clone git://github.com/ansible/ansible.git --recursive
$ cd ./ansible
```

http://docs.ansible.com/ansible/intro_installation.html

This should definitely work for you have you get 2.1 installed (and configure a new module path or use the `-M` flag when running `ansible-playbook` to specify a path.  Let me know if you have any questions.

**Comment by geepees2015** [comment]
Tried that and seeing following error:

ansible-playbook  -i hosts test1-interface.yml -vvv --check
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test1-interface.yml **************************************************
1 plays in test1-interface.yml

PLAY [interface testing] *******************************************************

TASK [nxos_ip_interface] *******************************************************
task path: /usr/share/ansible/samples/test1-interface.yml:12
<setup.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<setup.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1462060541.37-90528611705994`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1462060541.37-90528611705994`" )'
<setup.com> PUT /tmp/tmpkUYteV TO /root/.ansible/tmp/ansible-tmp-1462060541.37-90528611705994/nxos_ip_interface
<setup.com> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1462060541.37-90528611705994/nxos_ip_interface; rm -rf "/root/.ansible/tmp/ansible-tmp-1462060541.37-90528611705994/" > /dev/null 2>&1'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py", line 526, in <module>
    main()
  File "/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py", line 452, in main
    validate_params(addr, interface, mask, version, state, intf_type, module)
  File "/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py", line 416, in validate_params
    if is_default(interface, module) == "DNE":
  File "/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py", line 190, in is_default
    body = execute_show_command(command, module)[0]
  File "/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py", line 147, in execute_show_command
    response = execute_show(cmds, module)
  File "/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py", line 136, in execute_show
    response = module.execute(cmds)
  File "/tmp/ansible_XU7u4E/ansible_modlib.zip/ansible/module_utils/nxos.py", line 246, in execute
  File "/tmp/ansible_XU7u4E/ansible_modlib.zip/ansible/module_utils/nxos.py", line 223, in connect
  File "/tmp/ansible_XU7u4E/ansible_modlib.zip/ansible/module_utils/nxos.py", line 175, in connect
  File "/tmp/ansible_XU7u4E/ansible_modlib.zip/ansible/module_utils/shell.py", line 114, in open
  File "/tmp/ansible_XU7u4E/ansible_modlib.zip/ansible/module_utils/shell.py", line 123, in receive
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 598, in recv
    raise socket.timeout()
socket.timeout

fatal: [setup.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "nxos_ip_interface"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py\", line 526, in <module>\n    main()\n  File \"/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py\", line 452, in main\n    validate_params(addr, interface, mask, version, state, intf_type, module)\n  File \"/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py\", line 416, in validate_params\n    if is_default(interface, module) == \"DNE\":\n  File \"/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py\", line 190, in is_default\n    body = execute_show_command(command, module)[0]\n  File \"/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py\", line 147, in execute_show_command\n    response = execute_show(cmds, module)\n  File \"/tmp/ansible_XU7u4E/ansible_module_nxos_ip_interface.py\", line 136, in execute_show\n    response = module.execute(cmds)\n  File \"/tmp/ansible_XU7u4E/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 246, in execute\n  File \"/tmp/ansible_XU7u4E/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 223, in connect\n  File \"/tmp/ansible_XU7u4E/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 175, in connect\n  File \"/tmp/ansible_XU7u4E/ansible_modlib.zip/ansible/module_utils/shell.py\", line 114, in open\n  File \"/tmp/ansible_XU7u4E/ansible_modlib.zip/ansible/module_utils/shell.py\", line 123, in receive\n  File \"/usr/lib/python2.7/site-packages/paramiko/channel.py\", line 598, in recv\n    raise socket.timeout()\nsocket.timeout\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test1-interface.retry

PLAY RECAP *********************************************************************
setup.com : ok=0    changed=0    unreachable=0    failed=1

**Comment by jedelman8** [comment]
Can you set transport to nxapi? There is a new param now bc they support SSH and nxapi. 

This is odd as I just tried them both today. Will try more tomorrow.

**Comment by geepees2015** [comment]
I put the transport as nxapi and this time I tried to configure an ip address on a routed interface. I did not see any ip getting configured and no errors were displayed ;
ansible-playbook  test1-interface.yml -vvv --check
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test1-interface.yml **************************************************
1 plays in test1-interface.yml

PLAY [interface testing] *******************************************************

TASK [nxos_ip_interface] *******************************************************
task path: /usr/share/ansible/samples/test1-interface.yml:11
<stepup.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<stepup.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1462079569.64-241680234387240`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1462079569.64-241680234387240`" )'
<stepup.com> PUT /tmp/tmpfUdqjk TO /root/.ansible/tmp/ansible-tmp-1462079569.64-241680234387240/nxos_ip_interface
<stepup.com> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1462079569.64-241680234387240/nxos_ip_interface; rm -rf "/root/.ansible/tmp/ansible-tmp-1462079569.64-241680234387240/" > /dev/null 2>&1'
changed: [stepup.com] => {"changed": true, "commands": ["interface ethernet1/46", "ip address 1.1.1.1/24"], "invocation": {"module_args": {"addr": "1.1.1.1", "host": "stepup.com", "interface": "Ethernet1/46", "mask": "24", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "port": null, "provider": null, "ssh_keyfile": null, "state": "present", "transport": "nxapi", "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "url_username": "admin", "use_ssl": false, "username": "admin", "validate_certs": true, "version": "v4"}, "module_name": "nxos_ip_interface"}}

PLAY RECAP *********************************************************************
stepup.com : ok=1    changed=1    unreachable=0    failed=0   

I manually configured an ip on the interface e1/46 just to get the xml output which looks as below and can help to understand if right parameters are passed ;

sh interface ethernet 1/46 | xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<nf:rpc-reply xmlns:nf="urn:ietf:params:xml:ns:netconf:base:1.0" xmlns="http://www.cisco.com/nxos:1.0:if_manager">
 nf:data
  <show>
   <interface>
    <**XML__INTF_ifeth>
     <__XML__PARAM_value>
      <__XML__INTF_output>Ethernet1/46</__XML__INTF_output>
     </__XML__PARAM_value>
     <__XML__OPT_Cmd_show_interface_if_eth___readonly**>
      <**readonly**>
       <TABLE_interface>
        <ROW_interface>
         <interface>Ethernet1/46</interface>
         <state>down</state>
         <state_rsn_desc>Administratively down</state_rsn_desc>
         <admin_state>down</admin_state>
         <share_state>Dedicated</share_state>
         <eth_hw_desc>100/1000/10000 Ethernet</eth_hw_desc>
         <eth_hw_addr>d8b1.90fb.41bd</eth_hw_addr>
         <eth_bia_addr>d8b1.90fb.41eb</eth_bia_addr>
         <eth_ip_addr>1.1.1.1</eth_ip_addr>
         <eth_ip_mask>24</eth_ip_mask>
         <eth_ip_prefix>1.1</eth_ip_prefix>
         <eth_mtu>1500</eth_mtu>
         <eth_bw>10000000</eth_bw>
         <eth_dly>10</eth_dly>
         <eth_reliability>255</eth_reliability>
         <eth_txload>1</eth_txload>
         <eth_rxload>1</eth_rxload>
         <medium>broadcast</medium>
         <eth_duplex>auto</eth_duplex>
         <eth_speed>auto-speed</eth_speed>
         <eth_beacon>off</eth_beacon>
         <eth_autoneg>on</eth_autoneg>
         <eth_in_flowctrl>off</eth_in_flowctrl>
         <eth_out_flowctrl>off</eth_out_flowctrl>
         <eth_mdix>off</eth_mdix>
         <eth_swt_monitor>off</eth_swt_monitor>
         <eth_ethertype>0x8100</eth_ethertype>
         <eth_eee_state>n/a</eth_eee_state>
         <eth_link_flapped>5week(s) 3day(s)</eth_link_flapped>
         <eth_clear_counters>30w6d</eth_clear_counters>
         <eth_reset_cntr>0</eth_reset_cntr>
         <eth_load_interval1_rx>30</eth_load_interval1_rx>
         <eth_inrate1_bits>0</eth_inrate1_bits>
         <eth_inrate1_pkts>0</eth_inrate1_pkts>
         <eth_load_interval1_tx>30</eth_load_interval1_tx>
         <eth_outrate1_bits>0</eth_outrate1_bits>
         <eth_outrate1_pkts>0</eth_outrate1_pkts>
         <eth_inucast>1180087</eth_inucast>
         <eth_inmcast>0</eth_inmcast>
         <eth_inbcast>851</eth_inbcast>
         <eth_inpkts>1180938</eth_inpkts>
         <eth_inbytes>319526914</eth_inbytes>
         <eth_jumbo_inpkts>0</eth_jumbo_inpkts>
         <eth_storm_supp>0</eth_storm_supp>
         <eth_runts>0</eth_runts>
         <eth_giants>0</eth_giants>
         <eth_crc>0</eth_crc>
         <eth_nobuf>0</eth_nobuf>
         <eth_inerr>0</eth_inerr>
         <eth_frame>0</eth_frame>
         <eth_overrun>0</eth_overrun>
         <eth_underrun>0</eth_underrun>
         <eth_ignored>0</eth_ignored>
         <eth_watchdog>0</eth_watchdog>
         <eth_bad_eth>0</eth_bad_eth>
         <eth_bad_proto>0</eth_bad_proto>
         <eth_in_ifdown_drops>0</eth_in_ifdown_drops>
         <eth_dribble>0</eth_dribble>
         <eth_indiscard>0</eth_indiscard>
         <eth_inpause>0</eth_inpause>
         <eth_outucast>784324</eth_outucast>
         <eth_outmcast>15615829</eth_outmcast>
         <eth_outbcast>11708</eth_outbcast>
         <eth_outpkts>16411861</eth_outpkts>
         <eth_outbytes>1106241715</eth_outbytes>
         <eth_jumbo_outpkts>0</eth_jumbo_outpkts>
         <eth_outerr>0</eth_outerr>
         <eth_coll>0</eth_coll>
         <eth_deferred>0</eth_deferred>
         <eth_latecoll>0</eth_latecoll>
         <eth_lostcarrier>0</eth_lostcarrier>
         <eth_nocarrier>0</eth_nocarrier>
         <eth_babbles>0</eth_babbles>
         <eth_outdiscard>0</eth_outdiscard>
         <eth_outpause>0</eth_outpause>
        </ROW_interface>
       </TABLE_interface>
      </**readonly**>
     </**XML__OPT_Cmd_show_interface_if_eth___readonly**>
    </__XML__INTF_ifeth>
   </interface>
  </show>
 /nf:data
/nf:rpc-reply

**Comment by geepees2015** [comment]
Looks like the xml from the device got parsed. I am doing it again:

```
    <interface>Ethernet1/46</interface>
     <state>down</state>
     <state_rsn_desc>Administratively down</state_rsn_desc>
     <admin_state>down</admin_state>
     <share_state>Dedicated</share_state>
     <eth_hw_desc>100/1000/10000 Ethernet</eth_hw_desc>
     <eth_hw_addr>d8b1.90fa.41bd</eth_hw_addr>
     <eth_bia_addr>d8b1.90fa.41eb</eth_bia_addr>
     <eth_ip_addr>180.180.180.1</eth_ip_addr>
     <eth_ip_mask>24</eth_ip_mask>
     <eth_ip_prefix>180</eth_ip_prefix>
```

**Comment by geepees2015** [comment]
[mydow.docx](https://github.com/jedelman8/nxos-ansible/files/243984/mydow.docx)

The above shows the wireshark capture and I don' see any parameters getting passed to the interface. The only post i see is ' show interface ethernet1/46'

Is nxos_ip_interface the right module ?

**Comment by jedelman8** [comment]
You ran it in check mode with `--check` so yes, it will not make the change.  That is to find out **if** a change would get made and if so, what commands would get sent.  Can you re-run without `--check`?

**Comment by geepees2015** [comment]
That worked and one step closer.

How do I create svi because the task nxos_ip_interface does not do that ? Also, if an interface is switchport,how to convert to routed port or vice versa ?

Thanks for all your help.

**Comment by jedelman8** [comment]
You use nxos_interface  - it creates the SVI and other logical interfaces. Same module has a param called `mode` - you set it to "layer2" or "layer3" based on if you want a routed or switched port. :)

**Comment by geepees2015** [comment]
Awesome !

thanks for all your help and looks like "transport" params needs to be added for every task.

**Comment by jedelman8** [comment]
You actually don't.  You can use the `provider` parameter to pass in a dictionary object:

Their description: "- provider
        Convience method that allows all [nxos] arguments to be passed as a
        dict object.  All constraints (required, choices, etc) must be met
        either by individual arguments or values in this dict. [Default: None]"

So, in a vars file like `group_vars/all.yml` you could have:

```
---
provider:
  username: cisco
  password: cisco
  transport: nxapi
```

and then in your playbook (need to use yaml vertical syntax:

```
  - name: TESTING
    nxos_interface:
      provider: "{{ provider }}"
      interface: Eth1/1
      mode: layer2 
```

Haven't tested this  yet, but that's what it is meant for...

BTW, if you remove transport=nxapi, does it still not work?  Let me know for each module.

Thank you.

**Comment by geepees2015** [comment]
If i remove transport=nxapi, it will not work. I will try the provider and let you know.
Thanks !

**Comment by jedelman8** [comment]
Okay, for when you don't have transport=nxapi...

you do have SSH enabled and you can SSH enable from the ansible machine to the machine, correct?  No ACLs, etc. ? Just need to confirm.

**Comment by geepees2015** [comment]
Will try ssh. Btw, do you have any snmp related lib's ?

Thanks !

**Comment by jedelman8** [comment]
I love snmp_device_version for inventorying devices:  https://github.com/networklore/ansible-snmp/tree/master/library

@ogenstad also has a few more for collecting facts and even more managing Cisco devices: https://github.com/networklore/ansible-cisco-snmp

**Comment by geepees2015** [comment]
After removing the nxapi, I get the following tracebacks:

```
PLAYBOOK: test2-interface.yml **************************************************
1 plays in test2-interface.yml

PLAY [interface testing] *******************************************************

TASK [nxos_interface] **********************************************************
task path: /usr/share/ansible/samples/test2-interface.yml:11
<stepup.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<stepup.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1462121955.88-31760764525377 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1462121955.88-31760764525377 `" )'
<stepup.com> PUT /tmp/tmpz4o8cD TO /root/.ansible/tmp/ansible-tmp-1462121955.88-31760764525377/nxos_interface
<stepup.com> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1462121955.88-31760764525377/nxos_interface; rm -rf "/root/.ansible/tmp/ansible-tmp-1462121955.88-31760764525377/" > /dev/null 2>&1'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_wgrx0G/ansible_module_nxos_interface.py", line 718, in <module>
    main()
  File "/tmp/ansible_wgrx0G/ansible_module_nxos_interface.py", line 629, in main
    available_features = get_available_features(feature, module)
  File "/tmp/ansible_wgrx0G/ansible_module_nxos_interface.py", line 163, in get_available_features
    body = execute_show_command(command, module)
  File "/tmp/ansible_wgrx0G/ansible_module_nxos_interface.py", line 570, in execute_show_command
    response = execute_show(cmds, module)
  File "/tmp/ansible_wgrx0G/ansible_module_nxos_interface.py", line 558, in execute_show
    response = module.execute(cmds)
  File "/tmp/ansible_wgrx0G/ansible_modlib.zip/ansible/module_utils/nxos.py", line 246, in execute
  File "/tmp/ansible_wgrx0G/ansible_modlib.zip/ansible/module_utils/nxos.py", line 223, in connect
  File "/tmp/ansible_wgrx0G/ansible_modlib.zip/ansible/module_utils/nxos.py", line 175, in connect
  File "/tmp/ansible_wgrx0G/ansible_modlib.zip/ansible/module_utils/shell.py", line 114, in open
  File "/tmp/ansible_wgrx0G/ansible_modlib.zip/ansible/module_utils/shell.py", line 123, in receive
  File "/usr/lib/python2.7/site-packages/paramiko/channel.py", line 598, in recv
    raise socket.timeout()
socket.timeout

fatal: [stepup.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "nxos_interface"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_wgrx0G/ansible_module_nxos_interface.py\", line 718, in <module>\n    main()\n  File \"/tmp/ansible_wgrx0G/ansible_module_nxos_interface.py\", line 629, in main\n    available_features = get_available_features(feature, module)\n  File \"/tmp/ansible_wgrx0G/ansible_module_nxos_interface.py\", line 163, in get_available_features\n    body = execute_show_command(command, module)\n  File \"/tmp/ansible_wgrx0G/ansible_module_nxos_interface.py\", line 570, in execute_show_command\n    response = execute_show(cmds, module)\n  File \"/tmp/ansible_wgrx0G/ansible_module_nxos_interface.py\", line 558, in execute_show\n    response = module.execute(cmds)\n  File \"/tmp/ansible_wgrx0G/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 246, in execute\n  File \"/tmp/ansible_wgrx0G/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 223, in connect\n  File \"/tmp/ansible_wgrx0G/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 175, in connect\n  File \"/tmp/ansible_wgrx0G/ansible_modlib.zip/ansible/module_utils/shell.py\", line 114, in open\n  File \"/tmp/ansible_wgrx0G/ansible_modlib.zip/ansible/module_utils/shell.py\", line 123, in receive\n  File \"/usr/lib/python2.7/site-packages/paramiko/channel.py\", line 598, in recv\n    raise socket.timeout()\nsocket.timeout\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test2-interface.retry

PLAY RECAP *********************************************************************
stepup.com : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by jedelman8** [comment]
can you confirm you can ssh to the switch directly from the ansible machine?

**Comment by geepees2015** [comment]
that works as i tried it earlier. Don't have any iptables on host or acl's on switch.

**Comment by jedelman8** [comment]
Is this a local device?  What kind of latency is between you and device?

I'm going to ping @privateip - and see if there a way to increase the timeout value...I can test again myself later, but last I checked on my 9Ks, it was all good.

**Comment by geepees2015** [comment]
PING stepup.com (30.30.30.30) 56(84) bytes of data.
64 bytes from stepup.com (30.30.30.30): icmp_seq=1 ttl=253 time=0.491 ms
64 bytes from stepup.com (30.30.30.30): icmp_seq=2 ttl=253 time=0.404 ms
64 bytes from stepup.com (30.30.30.30): icmp_seq=3 ttl=253 time=0.375 ms
64 bytes from stepup.com (30.30.30.30): icmp_seq=4 ttl=253 time=0.442 ms

It is on same network and all are fat pipes with low traffic

**Comment by geepees2015** [comment]
The snmp module throws me following error ;

task path: /usr/share/ansible/samples/test3snmp-interface.yml:16
<stepup.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<stepup.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1462125488.38-50316287307581`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1462125488.38-50316287307581`" )'
<stepup.com> PUT /tmp/tmptJUWtS TO /root/.ansible/tmp/ansible-tmp-1462125488.38-50316287307581/snmp_device_version
<stepup.com> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1462125488.38-50316287307581/snmp_device_version; rm -rf "/root/.ansible/tmp/ansible-tmp-1462125488.38-50316287307581/" > /dev/null 2>&1'
fatal: [stepup.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"authkey": "abc12345", "host": "stepup.com", "integrity": "md5", "level": "authPriv", "password": “xxxxx”, "privacy": "aes", "privkey": "def67890", "transport": "nxapi", "username": "admin", "version": "3"}, "module_name": "snmp_device_version"}, "msg": "unsupported parameter for module: password"}

The file parameters I pass are as follows:
- snmp_device_version:
     host={{ inventory_hostname }}
     transport=nxapi
     version=3
     level=authPriv
     integrity=md5
     privacy=aes
     username=snmpman
     authkey=abc12345
     privkey=def67890
     username=admin
     password="xxxxxxx"

**Comment by ogenstad** [comment]
Regarding the timeout I actually posted a PR which has been merged. This was for the IOS modules. If there are timeout issues with NXOS another fix needs to be done for that. Compare [ios.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/ios.py) to [nxos.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/nxos.py) (looking specifically at timeout).

**Comment by ogenstad** [comment]
For the snmp_device_version you have too many parameters. You are notified of this in the error message: "msg": "unsupported parameter for module: password"

**Comment by jedelman8** [comment]
Thanks @ogenstad, will checkout the timeout PR you have.

**Comment by geepees2015** [comment]
I put the timeout in the nx_os.py in the same places where the function is called and I see the error:
@ogenstad 
 File "<unknown>", line 40
    timeout=dict(default=10, type='int')
          ^

**Comment by geepees2015** [comment]
@ogenstad Seeing following error on snmp:
FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"authkey": "abc12345", "community": "False", "host": "stepup.com", "integrity": "md5", "level": "authPriv", "port": 161, "privacy": "aes", "privkey": "def67890", "username": "snmpman", "version": "3"}, "module_name": "snmp_device_version"}, "msg": "'str' object has no attribute '_ErrorIndication__descr'"}

Which one is the string object ?

Thanks !

**Comment by ogenstad** [comment]
The thing the timeout patch solves is that it gives the end user the ability to change default timeout of 10 seconds. The problem I had was when running "write mem" some times it would take 4 seconds, while it could take 12 or more other times. This caused the task to fail. So you would need to change more that just that line.

For the SNMP issue it looks like I'm not catching the error in the correct way. Could be something that I did or some change in the underlying pysnmp lib. Pehaps you can open an issue over here: https://github.com/networklore/ansible-snmp/issues It would probably be easier to handle these issues separately.

**Comment by geepees2015** [comment]
Sure. Thanks !
