### ISSUE TITLE
NX-API or CLI?

### ISSUE THREAD

**Issue by adosztal** [jedelman8/nxos-ansible#91]
I somewhat know the differences between the two but there's something I haven't found yet. Are there any pros of using NX-API as transport with Ansible compared to CLI?

These are what I found so far:
- NX-API can be processed better using Python but Ansible "hides" that part, and provides the same YAML output for both
- I can use certificate keys for user authentication with CLI but not with NX-API
- All NXOS modules support both transport modes

Based on the above, CLI seems to be a better choice but I fear I missed something here.

**Comment by kaisero** [comment]
NX-API returns structured data which makes parsing output easier than CLI output. If you only use NX-API to push commands and not validate anything afterwards you may as well use CLI. If you want to work with the data returned by NX-OS you should stick to NX-API.

**Comment by adosztal** [comment]
I know the raw protocol output is different but Ansible provides the same JSON formatted output for both. For example, these two provides the same output:

```
---
- hosts: nx1
  connection: local

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      transport: cli

  tasks:
    - name: Gather NX-OS facts
      nxos_facts:
        host: "{{ inventory_hostname }}"
        username: ansible
        ssh_keyfile: "~/.ssh/id_rsa"
        transport: cli
      register: facts

    - debug: msg="{{ facts }}"
```

```
---
- hosts: nx1
  connection: local

  tasks:
    - name: Gather NX-OS facts - NXAPI
      nxos_facts:
        host: "{{ inventory_hostname }}"
        username: admin
        password: admin
        transport: nxapi
      register: facts

    - debug: msg="{{ facts }}"
```

**Comment by jedelman8** [comment]
Right because by default, the command getting sent to the device when transport is `cli` is `show command | json`  

On a side note, I don't mind questions on this repo at all, but the modules in this repo are officially deprecated as they are coming from ansible core now.
