### ISSUE TITLE
nxos_interface assistance

### ISSUE THREAD

**Issue by nncse** [jedelman8/nxos-ansible#92]
Hi Jason et al,

I am an Ansible novice and came across your blog "Network Automation with Ansible - Dynamically Configuring Interface Descriptions".  I was able to get through tasks 1 and 2 but then for task 3, I ran into some issues where in it seems the "local_interface" and/or "args" is invalid. I have copied my output below including the yaml file. I hope you would be able to shed some light on what I am missing or doing wrong. 

Thank you very much in advance for any help.

YAML file:
=======

---
- name: AUTO CONFIGURE PORT DESCRIPTIONS (NXOS)
  hosts: nxos
  gather_facts: no
  connection: local

  tasks:

    - name: GET LLDP NEIGHBORS
      ntc_show_command:
        connection=ssh
        platform=cisco_nxos
        command='show lldp neighbors'
        host={{ inventory_hostname }}
        username={{ username }}
        password={{ password }}
      register: neighbors_nxos
      
    - debug: var=neighbors_nxos

    - name: CONFIG PORT
      nxos_interface: 
         interface={{ item.local_interface }} 
         description='Links to {{ item.neighbor_interface }} on {{ item.neighbor }}'
         host={{ inventory_hostname }}
         username={{ username }}
         password={{ password }}
      with_items: neighbors_nxos

OUTPUT:
======

user@e7ch1glmf01:~/ansible-files$ sudo ansible-playbook -i hosts.lab auto-config-port-descriptions_nxos.yaml -v
Using /home/user/ansible-files/ansible.cfg as config file

PLAY [AUTO CONFIGURE PORT DESCRIPTIONS (NXOS)] *********************************

TASK [GET LLDP NEIGHBORS] ******************************************************
ok: [c3548] => {"changed": false, "response": [{"local_interface": "Eth1/43", "neighbor": "a7010", "neighbor_interface": "Ethernet49"}, {"local_interface": "Eth1/44", "neighbor": "a7124", "neighbor_interface": "Ethernet18"}, {"local_interface": "Eth1/45", "neighbor": "C3560G", "neighbor_interface": "Gi0/24"}, {"local_interface": "Eth1/46", "neighbor": "a7124", "neighbor_interface": "Ethernet24"}, {"local_interface": "Eth1/47", "neighbor": "c4948e_2", "neighbor_interface": "Te1/49"}], "response_list": []}

TASK [debug] *******************************************************************
ok: [c3548] => {
    "neighbors_nxos": {
        "changed": false, 
        "response": [
            {
                "local_interface": "Eth1/43", 
                "neighbor": "a7010", 
                "neighbor_interface": "Ethernet49"
            }, 
            {
                "local_interface": "Eth1/44", 
                "neighbor": "a7124", 
                "neighbor_interface": "Ethernet18"
            }, 
            {
                "local_interface": "Eth1/45", 
                "neighbor": "C3560G", 
                "neighbor_interface": "Gi0/24"
            }, 
            {
                "local_interface": "Eth1/46", 
                "neighbor": "a7124", 
                "neighbor_interface": "Ethernet24"
            }, 
            {
                "local_interface": "Eth1/47", 
                "neighbor": "c4948e_2", 
                "neighbor_interface": "Te1/49"
            }
        ], 
        "response_list": []
    }
}

TASK [CONFIG PORT] *************************************************************
fatal: [c3548]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'local_interface'\n\nThe error appears to have been in '/home/user/ansible-files/auto-config-port-descriptions_nxos.yaml': line 22, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: CONFIG PORT\n      ^ here\n"}
	to retry, use: --limit @/home/user/ansible-files/auto-config-port-descriptions_nxos.retry

PLAY RECAP *********************************************************************
c3548                      : ok=2    changed=0    unreachable=0    failed=1

**Comment by jedelman8** [comment]
Try this for the line with `with_items:`

```
with_items: "{{ neighbors_nxos }}"
```


Also, try and use backticks to format code when opening issues, etc. on GitHub.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by nncse** [comment]
Thanks Jason for the quick reply. I have tried it but same result. 

I have tried to replace the {{ item.local_interface }} with {{ item }} and the with_items using the actual interface (Ethernet1/47) and that works so I know the interaction between my ansible host and the switch has no problem.

**Comment by jedelman8** [comment]
Ah sorry. You need to iterate over nxos_interface.response 

Notice the response key in your debug output.

**Comment by jedelman8** [comment]
Oops I meant: 

neighbors_nxos.response 

On email :)

**Comment by nncse** [comment]
Thanks very much Jason! That was the issue and it is now resolved.
