### ISSUE TITLE
Problem with nxos_facts module

### ISSUE THREAD

**Issue by olex777** [jedelman8/nxos-ansible#95]
[17:10]root@dnetapp01:/etc/network/scripts/databases/playbook_ansible$ ansible-playbook 1_nxos_facts.yml -vvv
Using /etc/ansible/ansible.cfg as config file
SSH password:

PLAYBOOK: 1_nxos_facts.yml **********************************************************************************************************************************************************
1 plays in 1_nxos_facts.yml

PLAY [Collect NXOS facts] ***********************************************************************************************************************************************************
META: ran handlers

TASK [NX-OS Facts] ******************************************************************************************************************************************************************
task path: /etc/network/scripts/databases/playbook_ansible/1_nxos_facts.yml:10
Using module file /etc/network/scripts/ansible/lib/ansible/modules/network/nxos/nxos_facts.py
<10.255.252.2> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.255.252.2> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.255.252.2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642 `" && echo ansible-tmp-1488208234.33-150228641643642="` e cho /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642 `" ) && sleep 0'
<10.255.252.2> PUT /tmp/tmppgpQyw TO /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642/nxos_facts.py
<10.255.252.2> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642/ /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642/nxos_facts.py &&  sleep 0'
<10.255.252.2> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1488208234.33-150228641643642/nxos_facts.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1488208234.33-1502 28641643642/" > /dev/null 2>&1 && sleep 0'
fatal: [10.255.252.2]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "gather_subset": [
                "all"
            ],
            "host": "10.255.252.2",
            "password": "xxx",
            "port": null,
            "provider": {
                "auth_pass": "xxx",
                "authorize": true,
                "host": "10.255.252.2",
                "password": "xxx",
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "use_ssl": null,
                "username": "xxx",
                "validate_certs": null
            },
            "ssh_keyfile": null,
            "timeout": null,
            "transport": "cli",
            "use_ssl": null,
            "username": "xxx",
            "validate_certs": null
        }
    },
    "msg": "show system resources | json\r\r\n                                       ^\r\n% Invalid command at '^' marker.\r\n\rn7k-1-vdc-agg# "
}
        to retry, use: --limit @/etc/network/scripts/databases/playbook_ansible/1_nxos_facts.retry

PLAY RECAP **************************************************************************************************************************************************************************
10.255.252.2               : ok=0    changed=0    unreachable=0    failed=1
______________________________________________________________________________________
So for some reasons when I have invalid input on command next step of the module behaviour generation of the error and process iterrupted. Commands which have not "invalid input" works fine, but no output about them in module.

**Comment by fhlmbrg** [comment]
@olex777 this is a deprecated repo. Please submit your issue here instead https://github.com/ansible/ansible/issues
