### ISSUE TITLE
nxos_switchport remove vlan

### ISSUE THREAD

**Issue by Leggggg** [jedelman8/nxos-ansible#97]
Hello!

First off, I'm pretty new to github/ansible/python in general...so bear with me. I am venturing into network automation through ansible and ran into a potential issue while testing adding and removing vlan's from a trunk interface, in my case a port-channel.

As mentioned in other threads, I used state: present to build out the port channel allowed vlan's list, and state: absent to break it down when necessary. Example below:

Example Router Configuration

R1#
!
interface Po1
switchport
switchport mode trunk
switchport trunk allowed vlan 100, 200, 300
no shut
!

I used a host file, and host variable file outlining vlan id's I wanted to add or remove. Adding vlan's worked flawlessly...but when I would try to remove the vlan's, the last vlan I'd attempt to remove would never actually issue a "command: switchport trunk allowed vlan remove 300" for instance. It would just pass it as "ok".

What I realized after passing additional vlan id's to my file was that it would not remove the vlan if it was the last remaining vlan on the trunk. This is not a cisco limitation...and maybe it is intended behavior of nxos_switchport...but it just wasn't very clear.

I would propose at the very least that documentation is updated. Optionally it could issue command "switchport trunk allowed vlan none" if the vlan you are trying to remove is the last remaining vlan on the trunk.

playbook

- name: remove vlan from trunk
   nxos_switchport:
    interface: Po1
    mode: trunk
    trunk_vlans: {{ item.vlan_id }}
    state: absent
   with_items:
     -example

Take care,

Matt

**Comment by Leggggg** [comment]
HOST_VAR FILE
![image](https://user-images.githubusercontent.com/36499076/36999582-6a75de62-2075-11e8-9e70-906e13bd1c60.png)
ROLLBACK PLAYBOOK
![image](https://user-images.githubusercontent.com/36499076/36999558-5665da8a-2075-11e8-9f7b-52c73950ac4f.png)
PRE-CHECK "CONFIGURATION"
![image](https://user-images.githubusercontent.com/36499076/36999741-f486ade8-2075-11e8-893c-57ee6b15184e.png)
POST-CHECK "CONFIGURATION"
![image](https://user-images.githubusercontent.com/36499076/36999790-1624c62e-2076-11e8-8968-246d21945140.png)
ANSIBLE OUTPUT "CHANGED FOR VLAN1002
![image](https://user-images.githubusercontent.com/36499076/36999920-85af0130-2076-11e8-9e21-209a39c76ecd.png)
ANSIBLE OUTPUT "OK FOR VLAN2000" - EXPECTED COMMAND: "interface Po111";"switchport trunk allowed vlan remove 2000" or "switchport trunk allowed vlan none"
![image](https://user-images.githubusercontent.com/36499076/36999881-651eb492-2076-11e8-9af0-af34fbdf70c7.png)

**Comment by mtarking** [comment]
@Leggggg Check the README for this repo; it has been deprecated as all the modules have been pushed upstream and you should have them in the latest Ansible release. Any issues need to be filed under the Ansible official repo.

**Comment by Leggggg** [comment]
Thanks for the response. I'll be sure to do that.

**Comment by Leggggg** [comment]
https://github.com/ansible/ansible/issues/37046
