### ISSUE TITLE
Issue with nxos_vlan

### ISSUE THREAD

**Issue by joemsanchez** [jedelman8/nxos-ansible#98]
So getting the hang of the nx modules, but ran across an issue with nxos_vlan module.  Using the examples from http://docs.ansible.com/ansible/latest/modules/nxos_vlan_module.html#nxos-vlan-module, I get the same error for about ever example:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'list' object has no attribute 'split'
fatal: [NX01]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_wYPKyg/ansible_module_nxos_vlan.py\", line 615, in <module>\n    main()\n  File \"/tmp/ansible_wYPKyg/ansible_module_nxos_vlan.py\", line 593, in main\n    have = map_config_to_obj(module, os_platform)\n  File \"/tmp/ansible_wYPKyg/ansible_module_nxos_vlan.py\", line 516, in map_config_to_obj\n    obj = parse_vlan_options(module, os_platform, output, vlans)\n  File \"/tmp/ansible_wYPKyg/ansible_module_nxos_vlan.py\", line 497, in parse_vlan_options\n    obj['interfaces'] = parse_interfaces(module, vlan)\n  File \"/tmp/ansible_wYPKyg/ansible_module_nxos_vlan.py\", line 474, in parse_interfaces\n    for i in interfaces.split(','):\nAttributeError: 'list' object has no attribute 'split'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
I created other playbooks for example that use the nxos_static_route module, and I don't have any issues at all with those.  I'm using Ansible version 2.5.2.  Please let me know if you need any other info

**Comment by mtarking** [comment]
@joemsanchez Check the README for this repo; it has been deprecated as all the modules have been pushed upstream and you should have them in the latest Ansible release. Any issues need to be filed under the official Ansible repo. It looks like a string split trying to be performed on a list data structure.

**Comment by joemsanchez** [comment]
@mtarking ok thanks for the follow up.  I was using the example from the NX OS modules.  Pretty it was from the latest release, but I guess I could be wrong.  I also never say a message saying the module was deprecated, but either way I'll post something on the Ansible repo.  Thanks again!

**Comment by mtarking** [comment]
@joemsanchez Yeah, there's some confusion :-) I've seen folks post issues here before, but for them to get traction they'll need to be posted in the main Ansible repo. It's this particular repo that is deprecated since the modules were pulled upstream.

**Comment by joemsanchez** [comment]
Ohhhh ok gotcha, that makes sense.
